# NumPy

# Algebra Linear - Auto-valores e auto-vetores

* Determinando autovalores e autovetores de matrizes
* @CursoDS_ProfDanilo
* Prof. Dr. Danilo Morales Teixeira
* cursods.profdanilo@gmail.com

In [1]:
import numpy as np

In [8]:
X = np.array([[3,0,0],[0,3,2],[0,-1,0]])

In [9]:
autovalores,autovetores = np.linalg.eig(X)

In [10]:
autovalores

array([1., 2., 3.])

In [11]:
autovetores

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.70710678, -0.89442719,  0.        ],
       [-0.70710678,  0.4472136 ,  0.        ]])

* Os autovetores estão normalizados

In [20]:
Y = np.array([[4,-2],[1,1]])

In [21]:
autovalores,autovetores = np.linalg.eig(Y)

In [22]:
autovalores

array([3., 2.])

In [23]:
autovetores

array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])

In [28]:
det_X = np.linalg.det(X)

In [29]:
det_X

6.000000000000001

In [26]:
det_Y = np.linalg.det(Y)

In [30]:
det_Y

6.0