# NumPy - avançado

* Funções avançados da biblioteca NumPy
* @CursoDS_ProfDanilo
* Prof. Dr. Danilo Morales Teixeira
* cursods.profdanilo@gmail.com

* Importando biblioteca

In [1]:
import numpy as np

* Criando arranjo NumPy

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

* Função where

In [3]:
print(arr[np.where(arr%2==0)])

[ 2  4  6  8 10]


* Substituindo elementos com where

In [4]:
arr2 = np.where(arr%2==0,0,arr)

In [5]:
print(arr2)

[1 0 3 0 5 0 7 0 9 0]


* Substituindo elementos - Comando put

In [6]:
np.put(arr2,1,10)

In [7]:
print(arr2)

[ 1 10  3  0  5  0  7  0  9  0]


* Valores NaN

In [8]:
arr = np.array([1,2,4,5,np.nan,0,2,3,np.nan,np.nan,0,3,4,6])

In [9]:
print(np.isnan(arr))

[False False False False  True False False False  True  True False False
 False False]


In [10]:
np.where(np.isnan(arr))

(array([4, 8, 9]),)

In [11]:
arr = np.where(np.isnan(arr),10,arr)

In [12]:
print(arr)

[ 1.  2.  4.  5. 10.  0.  2.  3. 10. 10.  0.  3.  4.  6.]


* Reshape

In [13]:
arr = np.array([1,2,3,4,5,6])

In [14]:
arr2 = arr.reshape(2,3)

In [15]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [16]:
arr3 = arr.reshape(3,2)

In [17]:
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


* Comando stack

In [18]:
np.hstack(arr2)

array([1, 2, 3, 4, 5, 6])

* Valores em comum

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([1,12,3,45,23,67,4])

In [20]:
comum = np.intersect1d(a,b)

In [21]:
print(comum)

[1 3 4]


* Removendo valores em comum

In [22]:
np.setdiff1d(a,b)

array([ 2,  5,  6,  7,  8,  9, 10])

* Verificando se elemenos estão no arranjo

In [23]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [24]:
print(np.isin(a,[1,5,8]))

[ True False False False  True False False  True False False]


* Invertendo arranjo

In [25]:
print(np.flip(a))

[10  9  8  7  6  5  4  3  2  1]


* Ordenando elementos

In [26]:
arr = np.array([10,45,32,67,2,0,20,45,78])

In [27]:
arr = np.sort(arr)

In [28]:
print(arr)

[ 0  2 10 20 32 45 45 67 78]


In [29]:
arr2 = np.array([[2,6,1],[8,2,0],[0,3,1]])

In [30]:
print(arr2)

[[2 6 1]
 [8 2 0]
 [0 3 1]]


In [31]:
arr2_0 = np.sort(arr2)
print(arr2_0)

[[1 2 6]
 [0 2 8]
 [0 1 3]]


* Ordenando na linha

In [32]:
arr2_1 = np.sort(arr2,axis=1)
print(arr2_1)

[[1 2 6]
 [0 2 8]
 [0 1 3]]


* Ordenando na coluna

In [33]:
arr2_2 = np.sort(arr2,axis=0)
print(arr2_2)

[[0 2 0]
 [2 3 1]
 [8 6 1]]


* Repetir sequencia

In [34]:
arr = np.array([1,2,3])

In [35]:
arr2 = np.tile(arr,2)

In [36]:
print(arr2)

[1 2 3 1 2 3]


* Valores únicos

In [37]:
arr = np.array([1,2,3,4,1,4,0,2,3,1,0,5,10])

In [38]:
print(np.unique(arr))

[ 0  1  2  3  4  5 10]


* Valores únicos com contagem

In [ ]:
valores, contagem = np.unique(arr,return_counts=True)

In [ ]:
print(valores)

In [ ]:
print(contagem)